neptulon/models/base.py
# coding: utf-8

from sqlalchemy.ext.declarative import declared_attr
from neptulon.ext import db

class Base(db.Model):

    __abstract__ = True

    @declared_attr
    def id(cls):
        return db.Column('id', db.Integer, primary_key=True, autoincrement=True)

    @declared_attr
    def __tablename__(cls):
        return cls.__name__.lower()

    @classmethod
    def get(cls, id):
        return cls.query.filter(cls.id == id).first()

    @classmethod
    def get_multi(cls, ids):
        return [cls.get(i) for i in ids]

    def delete(self):
        db.session.delete(self)
        db.session.commit()

neptulon/models/pubkey.py
# coding: utf-8

import datetime
import sqlalchemy.exc

from neptulon.ext import db
from neptulon.utils import gen_fingerprint
from neptulon.models.base import Base

class RSAKey(Base):

    user_id = db.Column(db.Integer, unique=True, nullable=False, index=True)
    title = db.Column(db.String(255), nullable=False)
    rsa = db.Column(db.Text, nullable=False)
    fingerprint = db.Column(db.String(32), nullable=False)
    time = db.Column(db.DateTime, default=datetime.datetime.now)
    
    @classmethod
    def create(cls, user_id, title, rsa):
        fingerprint = gen_fingerprint(rsa)
        try:
            rsakey = cls(user_id=user_id, title=title, rsa=rsa, fingerprint=fingerprint)
            db.session.add(rsakey)
            db.session.commit()
            return rsakey
        except sqlalchemy.exc.IntegrityError:
            db.session.rollback()
            return None

    @classmethod
    def get_by_user_id(cls, user_id):
        return cls.query.filter_by(user_id=user_id).first()

    @classmethod
    def get_by_fingerprint(cls, fingerprint):
        return cls.query.filter_by(fingerprint=fingerprint).first()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

neptulon/views/admin.py
# coding:utf-8

import sys
from flask import Blueprint, request, redirect, url_for, render_template, flash, jsonify, abort, g
from neptulon.utils import need_admin
from neptulon.models import User, RSAKey

bp = Blueprint('admin', __name__, url_prefix='/admin')

@bp.route('/', methods=['GET'])
def index():
    admin = request.args.get('admin')
    users, total = User.list_users(admin=admin, start=g.start, limit=g.limit)
    return render_template('/admin.html', users=users,
            total=total, endpoint='admin.index', admin=admin)


@bp.route('/edit/<int:uid>', methods=['GET', 'POST'])
def edit(uid):
    u = User.get(uid)
    if not u:
        abort(403)

    if request.method == 'GET':
        return render_template('/admin_edit.html', user=u)

    name = request.form['name']
    email = request.form['email']
    password = request.form['password']
    real_name = request.form['real_name']

    if not (name and email and real_name):
        flash(u'你有些忘记填了', 'error')
        return render_template('/admin_edit.html', user=u.id)

    u.edit(name, email, password, real_name)
    return redirect(url_for('admin.index'))


@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('/register.html')

    name = request.form['name']
    email = request.form['email']
    password = request.form['password']
    real_name = request.form['real_name']
    if not (name and email and password and real_name):
        flash(u'你有些忘记填了', 'error')
        return render_template('/register.html')

    u = User.create(name, email, password, real_name)
    if not u:
        flash(u'已经存在, 登录去吧', 'error')
        return render_template('/register.html')

    if not u.send_doc_email():
        flash(u'不好，发送邮件失败', 'error')
        return render_template('/register.html')
    return redirect(url_for('admin.index'))


@bp.route('/delete_user', methods=['POST'])
def delete_user():
    user_id = request.form['user_id']
    user = User.get(user_id)
    if not user:
        return jsonify({'message': 'not found'}), 404

    pubkey = RSAKey.get_by_user_id(user_id)
    if pubkey:
        pubkey.delete()
    user.delete()

    return jsonify({'message': 'ok'}), 200


@bp.route('/sudo', methods=['POST'])
def sudo():
    user_id = request.form['user_id']
    user = User.get(user_id)
    if not user:
        return jsonify({'message': 'not found'}), 404

    user.sudo()
    return jsonify({'message': 'ok'}), 200


@bp.before_request
@need_admin
def access_control():
    pass

neptulon/views/oauth.py
# coding: utf-8

from datetime import datetime, timedelta
from flask import Blueprint, request, g, redirect, render_template, url_for, flash

from neptulon.ext import oauth
from neptulon.models import Grant, Token, Client, User
from neptulon.utils import need_login, need_admin, jsonize

bp = Blueprint('oauth', __name__, url_prefix='/oauth')
_THOUSAND_DAY = 86400 * 1000


@oauth.clientgetter
def load_client(client_id):
    return Client.get_by_client_id(client_id)


@oauth.grantgetter
def load_grant(client_id, code):
    return Grant.get_by_code_and_client(code, client_id)


@oauth.grantsetter
def save_grant(client_id, code, request, *args, **kwargs):
    expires = datetime.now() + timedelta(seconds=_THOUSAND_DAY)
    return Grant.create(g.user.id, client_id, code['code'],
            request.redirect_uri, request.scopes, expires=expires)


@oauth.tokengetter
def load_token(access_token=None, refresh_token=None):
    if access_token:
        return Token.get_by_access(access_token)
    return Token.get_by_refresh(refresh_token)


@oauth.tokensetter
def save_token(token, request, *args, **kwargs):
    Token.delete_by_client_and_user(request.client.client_id, request.user.id)
    expires = datetime.now() + timedelta(seconds=_THOUSAND_DAY)

    return Token.create(request.client.client_id, request.user.id, token['token_type'],
            token['access_token'], token['refresh_token'], expires, token['scope'])


@bp.route('/token', methods=['GET', 'POST'])
@oauth.token_handler
def access_token():
    return None


@bp.route('/revoke', methods=['POST'])
@oauth.revoke_handler
def revoke_token():
    pass


@bp.route('/authorize', methods=['GET', 'POST'])
@oauth.authorize_handler
@need_login
def authorize(*args, **kwargs):
    if request.method == 'GET':
        client_id = kwargs.get('client_id')
        client = Client.get_by_client_id(client_id)
        kwargs['client'] = client
        kwargs['user'] = g.user
        return render_template('authorize.html', **kwargs)

    return request.form.get('agree', type=bool, default=False)


@bp.route('/delete_token', methods=['POST'])
@need_login
@jsonize
def delete_token():
    token_id = request.form['token']
    token = Token.get(token_id)
    if not token:
        return {'message': 'not found'}, 404
    if token.user_id != g.user.id:
        return {'message': 'not allowed'}, 403
    token.delete()
    return {'message': 'ok'}


@bp.route('/client', methods=['GET', 'POST'])
@need_admin
def client():
    if request.method == 'GET':
        clients = Client.get_all(g.start, g.limit)
        return render_template('client.html', clients=clients)

    redirect_uri = request.form.get('redirect_uri', default='')
    name = request.form.get('name', default='')
    if not (redirect_uri and name):
        flash(u'缺少需要填写的', 'error')
        return redirect(url_for('oauth.client'))

    Client.create(name, [redirect_uri], ['email'])
    return redirect(url_for('oauth.client'))


@bp.route('/delete_client', methods=['POST'])
@need_admin
@jsonize
def delete_client():
    client_id = request.form['client']
    client = Client.get(client_id)
    client.delete()
    return {'message': 'ok'}


@bp.route('/authorized', methods=['GET'])
@need_login
def authorized_tokens():
    tokens = Token.get_by_user(g.user.id, g.start, g.limit)
    return render_template('authorized.html', tokens=tokens)


@bp.route('/api/me')
@oauth.require_oauth()
@jsonize
def me():
    user = request.oauth.user
    return user.to_dict(private=True), 200


@bp.route('/api/user/<user_id>')
@oauth.require_oauth()
@jsonize
def get_user(user_id):
    u = User.get(user_id)
    if not u:
        return {}, 404

    user = request.oauth.user
    private = bool(user.privilege) or user.id == user_id
    return u.to_dict(private=private), 200


@bp.route('/api/users')
@oauth.require_oauth()
@jsonize
def get_users():
    users, _ = User.list_users(g.start, g.limit)
    private = bool(request.oauth.user.privilege)
    return [u.to_dict(private=private) for u in users if u], 200

neptulon/views/ui.py
# coding: utf-8

from flask import (Blueprint, request, g, redirect, url_for,
                   session, render_template, flash, jsonify, make_response)
from flask.ext.mail import Message

from neptulon.ext import mail
from neptulon.config import MAIL_USERNAME
from neptulon.models import User, RSAKey
from neptulon.utils import need_login, login_user

bp = Blueprint('ui', __name__, url_prefix='/ui')


@bp.route('/', methods=['GET'])
@need_login
def index():
    return redirect(url_for('oauth.authorized_tokens'))


@bp.route('/refresh_token', methods=['POST'])
@need_login
def refresh_token():
    pubkey = RSAKey.get_by_user_id(g.user.id)
    if pubkey:
        pubkey.delete()
    g.user.refresh_token()
    return jsonify({'message': g.user.token}), 200


@bp.route('/download_config')
@need_login
def download_config():
    resp = make_response(render_template('/ricebook-template.mobileconfig', username=g.user.name, password=g.user.token))
    resp.headers['Content-Type'] = "application/octet-stream"
    resp.headers['Pragma'] = "No-cache"
    resp.headers['Cache-Control'] = "No-cache"
    resp.headers['Content-Disposition'] = "attachment; filename='ricebook.mobileconfig'"
    return resp


@bp.route('/download_surge_config')
@need_login
def download_surge_config():
    resp = make_response(render_template('/surge-template.conf', username=g.user.name, password=g.user.token))
    resp.headers['Content-Type'] = "application/octet-stream"
    resp.headers['Pragma'] = "No-cache"
    resp.headers['Cache-Control'] = "No-cache"
    resp.headers['Content-Disposition'] = "attachment; filename='nova.conf'"
    return resp


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        if not g.user:
            return render_template('/login.html')
        return redirect(url_for('ui.index'))

    name = request.form['name']
    password = request.form['password']
    if not (name and password):
        flash(u'你有些忘记填了', 'error')
        return render_template('/login.html')

    u = User.get_by_name(name) or User.get_by_email(name)
    if not (u and u.check_password(password)):
        flash(u'密码错了, 或者你就不存在啊', 'error')
        return render_template('/login.html')

    login_user(u)

    redir = request.values.get('redirect', url_for('ui.index'))
    return redirect(redir)


@bp.route('/password', methods=['GET', 'POST'])
@need_login
def password():
    if request.method == 'GET':
        return render_template('/password.html')

    password = request.form['password']
    confirm_password = request.form['confirm_password']
    if password != confirm_password:
        flash(u'两次输入不对, 你是鱼么这么快就忘记了', 'error')
        return render_template('/password.html')

    g.user.set_password(password)
    return redirect(url_for('ui.index'))


@bp.route('/pubkey', methods=['GET'])
@need_login
def pubkeys():
    pubkey = RSAKey.get_by_user_id(g.user.id)
    return render_template('/pubkeys.html', pubkey=pubkey)


@bp.route('/add_pubkey', methods=['GET', 'POST'])
@need_login
def add_pubkey():
    if request.method == 'GET':
        return render_template('/add_pubkey.html')

    title = request.form['title']
    pkey = request.form['pkey']

    pubkey = RSAKey.get_by_user_id(g.user.id)
    if pubkey:
        flash(u'已经存在一枚key了，只能添加一枚哦', 'error')
        return render_template('/add_pubkey.html')

    RSAKey.create(g.user.id, title, pkey)
    return redirect(url_for('ui.pubkeys'))


@bp.route('/delete_pubkey', methods=['POST'])
@need_login
def delete_pubkey():
    keyfp = request.form['keyfp']
    pubkey = RSAKey.get_by_fingerprint(keyfp)
    if pubkey:
        pubkey.delete()
    else:
        return jsonify({'message': 'pub key does not exist'}), 200
    return jsonify({'message': 'ok'}), 200


@bp.route('/forget_password', methods=['POST', 'GET'])
def forget_password():
    if request.method == 'GET':
        return render_template('/forget_password.html', email='')

    email = request.form['email']
    user = User.get_by_email(email)
    if not user:
        flash(u'没这个人啊', 'error')
        return render_template('/forget_password.html', email='')

    message = Message(
                subject=u'重置内网 OPENID 密码',
                sender=MAIL_USERNAME,
                recipients=[email]
            )
    message.html = render_template('/email/reset_password.html', user=user)
    mail.send(message)
    return render_template('/forget_password.html', email=email)


@bp.route('/reset_password/<token>', methods=['POST', 'GET'])
def reset_password(token):
    user = User.get_by_token(token)
    if not user:
        flash(u'没有这个人啊', 'error')
        return render_template('/reset_password.html', token=token)

    if request.method == 'GET':
        return render_template('/reset_password.html', token=token)

    password = request.form['password']
    confirm_password = request.form['confirm_password']
    if password != confirm_password:
        flash(u'两次输入不对, 你是鱼么这么快就忘记了', 'error')
        return render_template('/reset_password.html', token=token)

    user.set_password(password)
    user.refresh_token()
    login_user(user)
    return redirect(url_for('ui.index'))


@bp.route('/logout', methods=['GET', 'POST'])
@need_login
def logout():
    session.pop('id', None)
    return redirect(url_for('ui.login'))

neptulon/templates/add_pubkey.html
{% extends "/base.html" %}

{% block main %}
    <div class="login-form">
      <form action="{{ url_for('ui.add_pubkey') }}" method="POST">
        <div class="form-group">
          <input name="title" class="form-control login-field" type="text" placeholder="title">
        </div>
        <div class="form-group">
          <textarea name="pkey" class="form-control login-field" col="40" row="30" placeholder="key"></textarea>
        </div>
        {% with errors = get_flashed_messages(category_filter=['error'])%}
        {% if errors %}
        <div class="form-group">
          {% for error in errors %}
          <label class="text-danger">
            <span class="fui-cross-circle"></span> {{ error }}
          </label>
          {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
        <button class="btn btn-primary btn-lg btn-block" type="submit">Go!</button>
      </form>
    </div>
{% endblock %}

neptulon/templates/admin.html
{% extends "/base.html" %}
{% import "/utils.html" as utils %}

{% block main %}
  <table class="table table-striped">
    <thead>
      <tr>
        <td>Name</td>
        <td>Realname</td>
        <td>Email</td>
        <td>Admin</td>
        <td>Ops</td>
      </tr>
    </thead>
    <tbody>
      {% for user in users%}
        <tr>
            <td>{{ user.name }}</td>
            <td>{{ user.real_name }}</td>
            <td>{{ user.email }}</td>
            <td>
                {% if user.privilege %}
                <span class="fui-check"></span>
                {% else %}
                <span class="fui-cross"></span>
                {% endif %}
            </td>
            <td>
                {% if user.id != g.user.id %}
                <a id="delete" class="btn btn-xs btn-warning" data-user-id="{{ user.id }}">嫑了</a>
                {% if user.privilege %}
                <a id="sudo" class="btn btn-xs btn-success" data-user-id="{{ user.id }}"> unsudo </a>
                {% else %}
                <a id="sudo" class="btn btn-xs btn-danger" data-user-id="{{ user.id }}"> sudo </a>
                {% endif %}
                {% endif %}
                <a class="btn btn-xs btn-info" href="{{ url_for('admin.edit', uid=user.id) }}"> edit </a>
            </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {{utils.paginator(g.start, total, g.limit, endpoint, admin=admin)}}
{% endblock %}

{% block bottom_script %}
<script>
  $('a#delete').click(function (){
    var self = $(this);
    $.post('{{url_for('admin.delete_user')}}', {user_id: self.data('user-id')}, function (){
      self.parent().parent().remove();
    });
  });
  $('a#sudo').click(function (){
    var self = $(this);
    $.post('{{url_for('admin.sudo')}}', {user_id: self.data('user-id')}, function (){
      location.reload();
    });
  });
</script>
{% endblock %}

neptulon/templates/admin_edit.html
{% extends "/base.html" %}

{% block main %}
    <div class="login-form">
      <form action="{{ url_for('admin.edit', uid=user.id) }}" method="POST">
        <div class="form-group">
          <input name="name" class="form-control login-field" type="text" value="{{ user.name }}">
          <label class="login-field-icon fui-user" for=""></label>
        </div>
        <div class="form-group">
          <input name="real_name" class="form-control login-field" type="text" value="{{ user.real_name }}">
          <label class="login-field-icon fui-tag" for=""></label>
        </div>
        <div class="form-group">
          <input name="email" class="form-control login-field" type="email" value="{{ user.email }}">
          <label class="login-field-icon fui-mail" for=""></label>
        </div>
        <div class="form-group">
          <input name="password" class="form-control login-field" type="password" placeholder="留空就是不修改">
          <label class="login-field-icon fui-lock" for=""></label>
        </div>
        {% with errors = get_flashed_messages(category_filter=['error'])%}
        {% if errors %}
        <div class="form-group">
          {% for error in errors %}
          <label class="text-danger">
            <span class="fui-cross-circle"></span> {{ error }}
          </label>
          {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
        <button class="btn btn-primary btn-lg btn-block" type="submit">Modify!</button>
      </form>
    </div>
{% endblock %}

neptulon/templates/authorize.html
{% extends "/base.html" %}

{% block main %}
<div class="col-md-3"></div>
<div class="col-md-6">
  <h3>{{ client.name }}</h3>
  <p>请求获取你的身份信息</p>
  <button class="btn btn-primary btn-small">给丫的</button>
  <button class="btn btn-warning btn-small">去死吧</button>

  <form action="{{ url_for('oauth.authorize') }}" method="POST">
    <input name="client_id" type="hidden" value="{{ client.client_id }}">
    <input name="scope" type="hidden" value="{{ scopes|join(' ') }}">
    <input name="response_type" type="hidden" value="{{ response_type }}">
    <input name="redirect_uri" type="hidden" value="{{ redirect_uri }}">
    {% if state %}
    <input name="state" type="hidden" value="{{ state }}">
    {% endif %}
    <input name="agree" type="text" value="">
  </form>
</div>
{% endblock %}

{% block more_css %}
form {display: none;}
.login-div {position: relative; padding: 38px 38px 267px; margin-bottom: 77px; color: #fff;}
{% endblock %}

{% block bottom_script %}
<script>
  $('.btn').click(function (){
    var self = $(this);
    if (self.hasClass('btn-primary')) {
      $('input[name=agree]').val('1');
    }
    $('form').submit();
  });
</script>
{% endblock %}

neptulon/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %} · Neptulon </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le styles -->
    <link href="/neptulon/static/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/neptulon/static/css/flat-ui.min.css" rel="stylesheet" type="text/css">
    <script src="/neptulon/static/js/jquery.min.js"></script>
    <script src="/neptulon/static/js/flat-ui.min.js"></script>
    {% block more_header %}{% endblock %}
    <style>
      {% block more_css %}{% endblock more_css %}
      nav.navbar {border-radius: 0!important;}
    </style>
    <!-- COLLECTED CSS -->
  </head>

  <body>

    {% block nav %}
    <!-- Docs master nav -->
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="navbar-header">
        <a href="{{ url_for('ui.index') }}" class="navbar-brand">Neptulon</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="{{ 'active' if request.path == url_for('oauth.authorized_tokens') else '' }}">
            <a href="{{ url_for('oauth.authorized_tokens') }}"><span class="fui-list-numbered"></span> OAuth2 授权列表</a>
          </li>
          {% if g.user and g.user.privilege %}
          <li class="{{ 'active' if request.path == url_for('admin.index') else '' }}">
            <a href="{{ url_for('admin.index') }}"><span class="fui-user"></span> 老子要管人</a>
          </li>
          <li class="{{ 'active' if request.path == url_for('admin.register') else '' }}">
            <a href="{{ url_for('admin.register') }}"><span class="fui-plus-circle"></span> 新员工入职啦</a>
          </li>
          <li class="{{ 'active' if request.path == url_for('oauth.client') else '' }}">
            <a href="{{ url_for('oauth.client') }}"><span class="fui-gear"></span> OAuth2 客户端管理</a>
          </li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ g.user.name or '你谁啊' }} <b class="caret"></b></a>
            <ul class="dropdown-menu">
              {% if g.user %}
              <li><a href="{{ url_for('ui.password') }}"><span class="fui-new"></span> 改个密码</a></li>
              {% if g.user.privilege %}
              <li class="divider"></li>
              <li><a href="{{ url_for('admin.index', admin=1) }}"><span class="fui-gear"></span> Admin 管理</a></li>
              {% endif %}
              <li class="divider"></li>
              <li class="{{ 'active' if request.path == url_for('ui.pubkeys') else '' }}">
                <a href="{{ url_for('ui.pubkeys') }}"><span class="fui-clip"></span> Pub Key / Token</a>
              </li>
              <li class="divider"></li>
              <li><a href="{{ url_for('ui.logout') }}"><span class="fui-power"></span> 再贱</a></li>
              {% else %}
              <li><a href="{{ url_for('ui.login') }}"><span class="fui-user"></span> 大爷来玩啊</a></li>
              {% endif %}
            </ul>
          </li>
        </ul>
        <div>
        </nav>
        {% endblock %}

        <!-- Docs page layout -->
        <div class="bs-header" id="content">
          <div class="container">
            {% block more_content_header %}{% endblock %}
          </div>
        </div>

        <div class="container bs-docs-container">
          <div class="row">
            {% block main %}
            {% endblock %}
          </div>
        </div>

        <!-- Footer ================================================== -->
        <footer class="footer container">
          {% block footer %}{% endblock %}
        </footer>

        <!-- Le javascript ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        {% block bottom_script %}{% endblock %}
        <!-- COLLECTED JS -->
      </body>
    </html>

neptulon/templates/forget_password.html
{% extends "/base.html" %}

{% block main %}
<div class="login-form">
  {% if email %}
  <p>已经发送重置邮件至 {{email}} </p>
  <p>跪恩吧</p>
  {% else %}
  <form action="{{ url_for('ui.forget_password') }}" method="POST">
    <div class="form-group">
      <input name="email" class="form-control login-field" type="email" placeholder="邮箱">
      <label class="login-field-icon fui-mail" for=""></label>
    </div>
    {% with errors = get_flashed_messages(category_filter=['error'])%}
    {% if errors %}
    <div class="form-group">
      {% for error in errors %}
      <label class="text-danger">
        <span class="fui-cross-circle"></span> {{ error }}
      </label>
      {% endfor %}
    </div>
    {% endif %}
    {% endwith %}
    <button class="btn btn-primary btn-lg btn-block" type="submit">真的忘记密码了求求你帮我重置吧</button>
  </form>
  {% endif %}
</div>
{% endblock %}

neptulon/templates/password.html
{% extends "/base.html" %}

{% block nav %}{% endblock %}

{% block main %}
<div class="login-div">
  <div class="login-screen">
    <div class="login-icon">
      <img src="/neptulon/static/img/svg/pencils.svg" alt="">
      <p>改密码</p>
    </div>
    <div class="login-form">
      <form action="{{ url_for('ui.password') }}" method="POST">
        <div class="form-group">
          <input name="password" class="form-control login-field" type="password" placeholder="密码">
          <label class="login-field-icon fui-lock" for=""></label>
        </div>
        <div class="form-group">
          <input name="confirm_password" class="form-control login-field" type="password" placeholder="再输入一次">
          <label class="login-field-icon fui-lock" for=""></label>
        </div>
        {% with errors = get_flashed_messages(category_filter=['error'])%}
        {% if errors %}
        <div class="form-group">
          {% for error in errors %}
          <label class="text-danger">
            <span class="fui-cross-circle"></span> {{ error }}
          </label>
          {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
        <button class="btn btn-primary btn-lg btn-block" type="submit">去吧基佬们!</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block more_css %}
body {background-color: #1abc9c;}
.login-div {position: relative; padding: 38px 38px 267px; margin-bottom: 77px; color: #fff;}
{% endblock %}

neptulon/templates/pubkeys.html
{% extends "/base.html" %}

{% block more_css %}
	.line-bottom {
		border-bottom: 1px #ddd solid;
		margin-bottom: 20px;
		padding-bottom: 20px;
	}
{% endblock %}

{% block main %}
<div class="col-md-8 col-md-offset-2 line-bottom">
	{% if pubkey %}
	<table class="table table-striped">
		<thead>
			<tr>
				<td>Fingerprint</td>
				<td>Title</td>
				<td>Ops</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>{{ pubkey.fingerprint }}</td>
				<td>{{ pubkey.title }}</td>
				<td>
					<a id="delete" class="pkeybtn btn btn-xs btn-warning" data-keyfp="{{ pubkey.fingerprint }}">嫑了</a>
				</td>
			</tr>
		</tbody>
	</table>
	{% else %}
	<p>没有 pubkey</p>
	<a class="btn btn-xs btn-info pull-left" href="/ui/add_pubkey">增加一枚</a> 
	{% endif %}
</div>

<div class="col-md-8 col-md-offset-2 line-bottom">
	<p>你的 token: {{ g.user.token }}</p>
	<a class="genbtn btn-xs btn-warning" href="#">更新 token</a> 
</div>

<div class="col-md-8 col-md-offset-2 line-bottom">
  <p>移动端 VPN 证书下载</p>
  <a class="btn-xs btn-info" href="{{ url_for('ui.download_config') }}" target="_blank">点我下载证书</a> 
</div>

<div class="col-md-8 col-md-offset-2 line-bottom">
  <p>Surge工具配置文件下载</p>
  <a class="btn-xs btn-info" href="{{ url_for('ui.download_surge_config') }}" target="_blank">点我下载Surge配置文件</a> 
</div>

<div class="col-md-8 col-md-offset-2 line-bottom">
  <p>Android操作系统下载方法</p>
  <ol>
    <li>选择添加vpn连接，类型选择IPSec Xauth PSK </li>
    <li>地址为vpn.ricebook.net </li>
    <li>identifier留空</li>
    <li>密码为ipsec</li>
  </ol>
</div>
{% endblock %}

{% block bottom_script %}
<script>
	$('.pkeybtn').click(function (){
		var self = $(this);
		$.post('/ui/delete_pubkey', {keyfp: self.data('keyfp')}, function (){
			self.parent().remove();
			location.reload();
		});
	});

	$('.genbtn').click(function(){
		var self = $(this);
		if (!confirm("确认删除么, 你的ssh公钥也都会被删除")) {
			return; 
		}
		$.post('/ui/refresh_token', {user_id: self.data('user-id')}, function(){
			location.reload();
		});
	});

	$('.downloadbtn').click(function(){
		var self = $(this);
		$.post('/ui/download_config', {user_id: self.data('user-id')}, function(){
			//alert("download...");
		});
	});
</script>
{% endblock %}